<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.tongji.sse</groupId>
        <artifactId>programming</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>Backends</artifactId>
    <packaging>pom</packaging>

    <!-- 列出所有微服务子模块文件夹 -->
    <modules>
        <module>common</module>
        <module>gateway</module>
        <module>services</module>
    </modules>

</project>
